#############################################################################
# Makefile for building: build/release/CarDesk
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  CarDesk.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile CarDesk.pro -spec linux-g++ CONFIG+=CAR_DESK_USE_T507_SDK
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCAR_DESK_DEVICE_PC -DAPP_BUILD_DATE=\"2026-05-30\" -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Ithirdparty/mupdf/include -isystem /usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/release/.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CarDesk1.0.0
DISTDIR = /data/CarDesk/build/release/.obj/CarDesk1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/data/CarDesk/thirdparty/mupdf/build/pc-release -lmupdf -lmupdf-third -ldbus-1 /usr/lib/x86_64-linux-gnu/libQt5MultimediaWidgets.so /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/release/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/automotivedriving.cpp \
		src/mainwindow.cpp \
		src/devicedetect.cpp \
		src/bluetoothmanager.cpp \
		src/mediamanager.cpp \
		src/videolistwindow.cpp \
		src/videoplaywindow.cpp \
		src/musicplayerwindow.cpp \
		src/radiowindow.cpp \
		src/phonewindow.cpp \
		src/diagnosticwindow.cpp \
		src/systemsettingwindow.cpp \
		src/drivingimagewindow.cpp \
		src/drivingimagenavbar.cpp \
		src/drivingimagepreviewtopbar.cpp \
		src/drivingimagesubtopbar.cpp \
		src/drivingimagesettingspage.cpp \
		src/drivingimageplaybackpage.cpp \
		src/ahdsettings.cpp \
		src/ahdrecordstore.cpp \
		src/imageviewingwindow.cpp \
		src/t507sdkbridge.cpp \
		src/ahdmanager.cpp \
		src/ahdlayout.cpp \
		src/ahdcamerapool.cpp \
		src/ahdpreviewwidget.cpp \
		src/otamanager.cpp \
		src/progressmonitor.cpp \
		src/appsignals.cpp \
		src/topbarwidget.cpp \
		src/faultcodedb.cpp \
		src/mcuserialreader.cpp \
		src/backlight.cpp \
		src/mupdfdocument.cpp \
		src/pinyin_dictionary.cpp qrc_resources.cpp \
		build/release/.moc/moc_mainwindow.cpp \
		build/release/.moc/moc_bluetoothmanager.cpp \
		build/release/.moc/moc_mediamanager.cpp \
		build/release/.moc/moc_videolistwindow.cpp \
		build/release/.moc/moc_videoplaywindow.cpp \
		build/release/.moc/moc_musicplayerwindow.cpp \
		build/release/.moc/moc_radiowindow.cpp \
		build/release/.moc/moc_phonewindow.cpp \
		build/release/.moc/moc_diagnosticwindow.cpp \
		build/release/.moc/moc_systemsettingwindow.cpp \
		build/release/.moc/moc_drivingimagewindow.cpp \
		build/release/.moc/moc_drivingimagenavbar.cpp \
		build/release/.moc/moc_drivingimagepreviewtopbar.cpp \
		build/release/.moc/moc_drivingimagesubtopbar.cpp \
		build/release/.moc/moc_drivingimagesettingspage.cpp \
		build/release/.moc/moc_drivingimageplaybackpage.cpp \
		build/release/.moc/moc_ahdsettings.cpp \
		build/release/.moc/moc_imageviewingwindow.cpp \
		build/release/.moc/moc_ahdmanager.cpp \
		build/release/.moc/moc_ahdcamerapool.cpp \
		build/release/.moc/moc_ahdpreviewwidget.cpp \
		build/release/.moc/moc_otamanager.cpp \
		build/release/.moc/moc_progressmonitor.cpp \
		build/release/.moc/moc_appsignals.cpp \
		build/release/.moc/moc_topbarwidget.cpp \
		build/release/.moc/moc_mcuserialreader.cpp
OBJECTS       = build/release/.obj/main.o \
		build/release/.obj/automotivedriving.o \
		build/release/.obj/mainwindow.o \
		build/release/.obj/devicedetect.o \
		build/release/.obj/bluetoothmanager.o \
		build/release/.obj/mediamanager.o \
		build/release/.obj/videolistwindow.o \
		build/release/.obj/videoplaywindow.o \
		build/release/.obj/musicplayerwindow.o \
		build/release/.obj/radiowindow.o \
		build/release/.obj/phonewindow.o \
		build/release/.obj/diagnosticwindow.o \
		build/release/.obj/systemsettingwindow.o \
		build/release/.obj/drivingimagewindow.o \
		build/release/.obj/drivingimagenavbar.o \
		build/release/.obj/drivingimagepreviewtopbar.o \
		build/release/.obj/drivingimagesubtopbar.o \
		build/release/.obj/drivingimagesettingspage.o \
		build/release/.obj/drivingimageplaybackpage.o \
		build/release/.obj/ahdsettings.o \
		build/release/.obj/ahdrecordstore.o \
		build/release/.obj/imageviewingwindow.o \
		build/release/.obj/t507sdkbridge.o \
		build/release/.obj/ahdmanager.o \
		build/release/.obj/ahdlayout.o \
		build/release/.obj/ahdcamerapool.o \
		build/release/.obj/ahdpreviewwidget.o \
		build/release/.obj/otamanager.o \
		build/release/.obj/progressmonitor.o \
		build/release/.obj/appsignals.o \
		build/release/.obj/topbarwidget.o \
		build/release/.obj/faultcodedb.o \
		build/release/.obj/mcuserialreader.o \
		build/release/.obj/backlight.o \
		build/release/.obj/mupdfdocument.o \
		build/release/.obj/pinyin_dictionary.o \
		build/release/.obj/qrc_resources.o \
		build/release/.obj/moc_mainwindow.o \
		build/release/.obj/moc_bluetoothmanager.o \
		build/release/.obj/moc_mediamanager.o \
		build/release/.obj/moc_videolistwindow.o \
		build/release/.obj/moc_videoplaywindow.o \
		build/release/.obj/moc_musicplayerwindow.o \
		build/release/.obj/moc_radiowindow.o \
		build/release/.obj/moc_phonewindow.o \
		build/release/.obj/moc_diagnosticwindow.o \
		build/release/.obj/moc_systemsettingwindow.o \
		build/release/.obj/moc_drivingimagewindow.o \
		build/release/.obj/moc_drivingimagenavbar.o \
		build/release/.obj/moc_drivingimagepreviewtopbar.o \
		build/release/.obj/moc_drivingimagesubtopbar.o \
		build/release/.obj/moc_drivingimagesettingspage.o \
		build/release/.obj/moc_drivingimageplaybackpage.o \
		build/release/.obj/moc_ahdsettings.o \
		build/release/.obj/moc_imageviewingwindow.o \
		build/release/.obj/moc_ahdmanager.o \
		build/release/.obj/moc_ahdcamerapool.o \
		build/release/.obj/moc_ahdpreviewwidget.o \
		build/release/.obj/moc_otamanager.o \
		build/release/.obj/moc_progressmonitor.o \
		build/release/.obj/moc_appsignals.o \
		build/release/.obj/moc_topbarwidget.o \
		build/release/.obj/moc_mcuserialreader.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		CarDesk.pro src/mainwindow.h \
		src/devicedetect.h \
		src/bluetoothmanager.h \
		src/mediamanager.h \
		src/videolistwindow.h \
		src/videoplaywindow.h \
		src/musicplayerwindow.h \
		src/radiowindow.h \
		src/phonewindow.h \
		src/diagnosticwindow.h \
		src/systemsettingwindow.h \
		src/drivingimagewindow.h \
		src/drivingimagenavbar.h \
		src/drivingimagepreviewtopbar.h \
		src/drivingimagesubtopbar.h \
		src/drivingimagesettingspage.h \
		src/drivingimageplaybackpage.h \
		src/ahdsettings.h \
		src/ahdrecordstore.h \
		src/imageviewingwindow.h \
		src/t507sdkbridge.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/ahdcamerapool.h \
		src/ahdpreviewwidget.h \
		src/otamanager.h \
		src/progressmonitor.h \
		src/appsignals.h \
		src/topbarwidget.h \
		src/faultcodedb.h \
		src/automotivedriving.h \
		src/mcuserialreader.h \
		src/backlight.h \
		src/mupdfdocument.h \
		src/pinyin_dictionary.h src/main.cpp \
		src/automotivedriving.cpp \
		src/mainwindow.cpp \
		src/devicedetect.cpp \
		src/bluetoothmanager.cpp \
		src/mediamanager.cpp \
		src/videolistwindow.cpp \
		src/videoplaywindow.cpp \
		src/musicplayerwindow.cpp \
		src/radiowindow.cpp \
		src/phonewindow.cpp \
		src/diagnosticwindow.cpp \
		src/systemsettingwindow.cpp \
		src/drivingimagewindow.cpp \
		src/drivingimagenavbar.cpp \
		src/drivingimagepreviewtopbar.cpp \
		src/drivingimagesubtopbar.cpp \
		src/drivingimagesettingspage.cpp \
		src/drivingimageplaybackpage.cpp \
		src/ahdsettings.cpp \
		src/ahdrecordstore.cpp \
		src/imageviewingwindow.cpp \
		src/t507sdkbridge.cpp \
		src/ahdmanager.cpp \
		src/ahdlayout.cpp \
		src/ahdcamerapool.cpp \
		src/ahdpreviewwidget.cpp \
		src/otamanager.cpp \
		src/progressmonitor.cpp \
		src/appsignals.cpp \
		src/topbarwidget.cpp \
		src/faultcodedb.cpp \
		src/mcuserialreader.cpp \
		src/backlight.cpp \
		src/mupdfdocument.cpp \
		src/pinyin_dictionary.cpp
QMAKE_TARGET  = CarDesk
DESTDIR       = build/release/
TARGET        = build/release/CarDesk


first: all
####### Build rules

build/release/CarDesk:  $(OBJECTS)  
	@test -d build/release/ || mkdir -p build/release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CarDesk.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		CarDesk.pro \
		resources.qrc
	$(QMAKE) -o Makefile CarDesk.pro -spec linux-g++ CONFIG+=CAR_DESK_USE_T507_SDK
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
CarDesk.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile CarDesk.pro -spec linux-g++ CONFIG+=CAR_DESK_USE_T507_SDK

qmake_all: FORCE


all: Makefile build/release/CarDesk

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/devicedetect.h src/bluetoothmanager.h src/mediamanager.h src/videolistwindow.h src/videoplaywindow.h src/musicplayerwindow.h src/radiowindow.h src/phonewindow.h src/diagnosticwindow.h src/systemsettingwindow.h src/drivingimagewindow.h src/drivingimagenavbar.h src/drivingimagepreviewtopbar.h src/drivingimagesubtopbar.h src/drivingimagesettingspage.h src/drivingimageplaybackpage.h src/ahdsettings.h src/ahdrecordstore.h src/imageviewingwindow.h src/t507sdkbridge.h src/ahdmanager.h src/ahdlayout.h src/ahdcamerapool.h src/ahdpreviewwidget.h src/otamanager.h src/progressmonitor.h src/appsignals.h src/topbarwidget.h src/faultcodedb.h src/automotivedriving.h src/mcuserialreader.h src/backlight.h src/mupdfdocument.h src/pinyin_dictionary.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/automotivedriving.cpp src/mainwindow.cpp src/devicedetect.cpp src/bluetoothmanager.cpp src/mediamanager.cpp src/videolistwindow.cpp src/videoplaywindow.cpp src/musicplayerwindow.cpp src/radiowindow.cpp src/phonewindow.cpp src/diagnosticwindow.cpp src/systemsettingwindow.cpp src/drivingimagewindow.cpp src/drivingimagenavbar.cpp src/drivingimagepreviewtopbar.cpp src/drivingimagesubtopbar.cpp src/drivingimagesettingspage.cpp src/drivingimageplaybackpage.cpp src/ahdsettings.cpp src/ahdrecordstore.cpp src/imageviewingwindow.cpp src/t507sdkbridge.cpp src/ahdmanager.cpp src/ahdlayout.cpp src/ahdcamerapool.cpp src/ahdpreviewwidget.cpp src/otamanager.cpp src/progressmonitor.cpp src/appsignals.cpp src/topbarwidget.cpp src/faultcodedb.cpp src/mcuserialreader.cpp src/backlight.cpp src/mupdfdocument.cpp src/pinyin_dictionary.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		ui/images/pict_volume.png \
		ui/images/butt_calling_num0_up.png \
		ui/images/butt_setting_check_up.png \
		ui/images/butt_home_radio_up.png \
		ui/images/butt_music_play_up.png \
		ui/images/butt_calling_num6_up.png \
		ui/images/music_buetooth_show.png \
		ui/images/butt_radio_list_down.png \
		ui/images/butt_calling_anwer_up.png \
		ui/images/pict_buetooth_on.png \
		ui/images/pict_callinglist_user.png \
		ui/images/pict_radio_fmbar.png \
		ui/images/radio_play_list_down.png \
		ui/images/butt_pdf_page_enter_up.png \
		ui/images/radio_list_down.png \
		ui/images/butt_home_bluetooth_phone_up.png \
		ui/images/butt_image_rotate_up.png \
		ui/images/butt_home_image_viewing_down.png \
		ui/images/butt_diagnosis_maintenance_up.png \
		ui/images/pict_volume_mute.png \
		ui/images/butt_radio_searchpre_down.png \
		ui/images/pic_driving_image_setting_direction_side.png \
		ui/images/butt_subnav_on.png \
		ui/images/butt_pdf_serch_result_pre_up.png \
		ui/images/topbar.png \
		ui/images/butt_diagnosis_abs_up.png \
		ui/images/butt_radio_searchnext_up.png \
		ui/images/pict_driving_image_video_recording.png \
		ui/images/butt_music_scan_up.png \
		ui/images/radio_list_up.png \
		ui/images/butt_diagnosis_controller_up.png \
		ui/images/pict_usb.png \
		ui/images/butt_home_system_settings_down.png \
		ui/images/butt_diagnosis_abs_down.png \
		ui/images/pict_brightness_high.png \
		ui/images/pict_buetooth.png \
		ui/images/butt_calling_num0_down.png \
		ui/images/pict_popalert_icon.png \
		ui/images/pict_clock_bg.png \
		ui/images/butt_tab_left_down.png \
		ui/images/butt_calling_num1_up.png \
		ui/images/butt_calling_num1_down.png \
		ui/images/butt_driving_image_setting_down.png \
		ui/images/butt_calling_num10_down.png \
		ui/images/butt_radio_search_down.png \
		ui/images/butt_calling_num2_down.png \
		ui/images/butt_music_scan_down.png \
		ui/images/butt_music_next_down.png \
		ui/images/butt_calling_num7_up.png \
		ui/images/butt_video_back_up.png \
		ui/images/butt_music_single_circle_up.png \
		ui/images/butt_calling_num3_down.png \
		ui/images/butt_calling_num4_down.png \
		ui/images/butt_music_random_up.png \
		ui/images/butt_calling_num12_down.png \
		ui/images/butt_diagnosis_controller_down.png \
		ui/images/butt_radiolist_search_up.png \
		ui/images/butt_calling_num5_down.png \
		ui/images/butt_home_audio_play_down.png \
		ui/images/butt_calling_num6_down.png \
		ui/images/butt_calling_num7_down.png \
		ui/images/butt_calling_hangup_down.png \
		ui/images/butt_radio_searchnext_down.png \
		ui/images/butt_calling_num12_up.png \
		ui/images/butt_back_up.png \
		ui/images/pict_music_album_icon.png \
		ui/images/butt_calling_num8_down.png \
		ui/images/butt_tab_center_on.png \
		ui/images/butt_calling_num9_down.png \
		ui/images/butt_home_driving_image_down.png \
		ui/images/butt_music_next_up.png \
		ui/images/butt_calling_del_down.png \
		ui/images/butt_music_collection_down.png \
		ui/images/butt_driving_image_playback_folder_down.png \
		ui/images/pict_volume_low.png \
		ui/images/butt_calling_mute_down.png \
		ui/images/butt_music_stop_up.png \
		ui/images/butt_music_list_up.png \
		ui/images/butt_calling_hangup_up.png \
		ui/images/butt_home_image_viewing_up.png \
		ui/images/butt_diagnosis_warning_down.png \
		ui/images/butt_back_down.png \
		ui/images/butt_calling_keyboard_up.png \
		ui/images/butt_diagnosis_maintenance_down.png \
		ui/images/butt_diagnosis_fault_down.png \
		ui/images/butt_calling_num2_up.png \
		ui/images/butt_radio_search_del_up.png \
		ui/images/butt_pdf_serch_result_pre_down.png \
		ui/images/butt_pdf_serch_result_next_down.png \
		ui/images/butt_tab_left_on.png \
		ui/images/butt_calling_num8_up.png \
		ui/images/butt_driving_image_playback_folder_up.png \
		ui/images/butt_diagnosis_fault_up.png \
		ui/images/butt_pdf_serch_result_next_up.png \
		ui/images/pict_brightness_low.png \
		ui/images/butt_home_bluetooth_phone_down.png \
		ui/images/pict_callinglist_state_2.png \
		ui/images/butt_radio_search_del_all_down.png \
		ui/images/butt_image_rotate_down.png \
		ui/images/pdf_view.png \
		ui/images/pic_driving_image_setting_direction_behind.png \
		ui/images/butt_radio_list_up.png \
		ui/images/butt_music_prev_down.png \
		ui/images/pict_popalert_fault_icon.png \
		ui/images/butt_setting_sound_field_up.png \
		ui/images/background.png \
		ui/images/butt_calling_mute_up.png \
		ui/images/pict_music_singer_icon.png \
		ui/images/prog_music_back.png \
		ui/images/butt_radio_search_del_all_up.png \
		ui/images/butt_home_diagnostic_maintenance_down.png \
		ui/images/butt_music_single_circle_down.png \
		ui/images/music_musiclist_file_down.png \
		ui/images/prog_music_fore.png \
		ui/images/butt_home_video_play_up.png \
		ui/images/music_play_musiclist_style_down.png \
		ui/images/pict_radio_mark.png \
		ui/images/butt_radio_search_up.png \
		ui/images/butt_tab_right_on.png \
		ui/images/music_play_musiclist_style_up.png \
		ui/images/butt_home_driving_image_up.png \
		ui/images/butt_calling_num3_up.png \
		ui/images/butt_calling_num9_up.png \
		ui/images/butt_home_radio_down.png \
		ui/images/pict_pdf_serch_writearea.png \
		ui/images/butt_calllinglist_answer_up.png \
		ui/images/video_play_top.png \
		ui/images/butt_music_musiclist_up.png \
		ui/images/butt_setting_close.png \
		ui/images/pic_calling_user.png \
		ui/images/butt_tab_center_down.png \
		ui/images/butt_diagnosis_warning_up.png \
		ui/images/pict_brightness_tips.png \
		ui/images/butt_calllinglist_answer_down.png \
		ui/images/butt_driving_image_video_up.png \
		ui/images/butt_setting_sound_field_down.png \
		ui/images/butt_music_prev_up.png \
		ui/images/butt_calling_del_up.png \
		ui/images/radio_play_list_up.png \
		ui/images/pict_volume_loud.png \
		ui/images/butt_home_system_settings_up.png \
		ui/images/butt_music_play_down.png \
		ui/images/butt_setting_choose_right.png \
		ui/images/pict_home_down.png \
		ui/images/butt_driving_image_playback_filelist_up.png \
		ui/images/butt_calling_num4_up.png \
		ui/images/butt_calling_keyboard_down.png \
		ui/images/butt_setting_open.png \
		ui/images/butt_home_diagnostic_maintenance_up.png \
		ui/images/pict_usb_on.png \
		ui/images/butt_music_musiclist_down.png \
		ui/images/pict_radio_ambar.png \
		ui/images/butt_music_circle_up.png \
		ui/images/butt_music_list_down.png \
		ui/images/butt_driving_image_setting_up.png \
		ui/images/butt_music_random_down.png \
		ui/images/butt_music_circle_down.png \
		ui/images/butt_setting_choose_left.png \
		ui/images/butt_video_back_down.png \
		ui/images/pict_callinglist_state_3.png \
		ui/images/butt_music_collection_up.png \
		ui/images/pict_home_up.png \
		ui/images/butt_calling_num5_up.png \
		ui/images/music_musiclist_up.png \
		ui/images/pict_popalert_bg.png \
		ui/images/music_show.png \
		ui/images/butt_home_audio_play_up.png \
		ui/images/butt_driving_image_playback_down.png \
		ui/images/image_imagellist_up.png \
		ui/images/butt_pdf_page_enter_down.png \
		ui/images/image_view.png \
		ui/images/music_musiclist_file_up.png \
		ui/images/butt_driving_image_video_down.png \
		ui/images/pict_driving_image_bottom.png \
		ui/images/butt_home_video_play_down.png \
		ui/images/butt_radio_search_del_down.png \
		ui/images/butt_driving_image_playback_filelist_down.png \
		ui/images/pict_brightness_mark.png \
		ui/images/pict_callinglist_state_1.png \
		ui/images/butt_calling_num10_up.png \
		ui/images/butt_calling_anwer_down.png \
		ui/images/butt_driving_image_playback_up.png \
		ui/images/butt_setting_check_down.png \
		ui/images/butt_music_stop_down.png \
		ui/images/butt_radio_searchpre_up.png \
		ui/images/pict_driving_image_tips_icon.png \
		ui/images/butt_tab_right_down.png \
		src/pinyin_table.txt
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: build/release/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/release/.moc/moc_predefs.h
build/release/.moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o build/release/.moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/release/.moc/moc_mainwindow.cpp build/release/.moc/moc_bluetoothmanager.cpp build/release/.moc/moc_mediamanager.cpp build/release/.moc/moc_videolistwindow.cpp build/release/.moc/moc_videoplaywindow.cpp build/release/.moc/moc_musicplayerwindow.cpp build/release/.moc/moc_radiowindow.cpp build/release/.moc/moc_phonewindow.cpp build/release/.moc/moc_diagnosticwindow.cpp build/release/.moc/moc_systemsettingwindow.cpp build/release/.moc/moc_drivingimagewindow.cpp build/release/.moc/moc_drivingimagenavbar.cpp build/release/.moc/moc_drivingimagepreviewtopbar.cpp build/release/.moc/moc_drivingimagesubtopbar.cpp build/release/.moc/moc_drivingimagesettingspage.cpp build/release/.moc/moc_drivingimageplaybackpage.cpp build/release/.moc/moc_ahdsettings.cpp build/release/.moc/moc_imageviewingwindow.cpp build/release/.moc/moc_ahdmanager.cpp build/release/.moc/moc_ahdcamerapool.cpp build/release/.moc/moc_ahdpreviewwidget.cpp build/release/.moc/moc_otamanager.cpp build/release/.moc/moc_progressmonitor.cpp build/release/.moc/moc_appsignals.cpp build/release/.moc/moc_topbarwidget.cpp build/release/.moc/moc_mcuserialreader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/release/.moc/moc_mainwindow.cpp build/release/.moc/moc_bluetoothmanager.cpp build/release/.moc/moc_mediamanager.cpp build/release/.moc/moc_videolistwindow.cpp build/release/.moc/moc_videoplaywindow.cpp build/release/.moc/moc_musicplayerwindow.cpp build/release/.moc/moc_radiowindow.cpp build/release/.moc/moc_phonewindow.cpp build/release/.moc/moc_diagnosticwindow.cpp build/release/.moc/moc_systemsettingwindow.cpp build/release/.moc/moc_drivingimagewindow.cpp build/release/.moc/moc_drivingimagenavbar.cpp build/release/.moc/moc_drivingimagepreviewtopbar.cpp build/release/.moc/moc_drivingimagesubtopbar.cpp build/release/.moc/moc_drivingimagesettingspage.cpp build/release/.moc/moc_drivingimageplaybackpage.cpp build/release/.moc/moc_ahdsettings.cpp build/release/.moc/moc_imageviewingwindow.cpp build/release/.moc/moc_ahdmanager.cpp build/release/.moc/moc_ahdcamerapool.cpp build/release/.moc/moc_ahdpreviewwidget.cpp build/release/.moc/moc_otamanager.cpp build/release/.moc/moc_progressmonitor.cpp build/release/.moc/moc_appsignals.cpp build/release/.moc/moc_topbarwidget.cpp build/release/.moc/moc_mcuserialreader.cpp
build/release/.moc/moc_mainwindow.cpp: src/mainwindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o build/release/.moc/moc_mainwindow.cpp

build/release/.moc/moc_bluetoothmanager.cpp: src/bluetoothmanager.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/bluetoothmanager.h -o build/release/.moc/moc_bluetoothmanager.cpp

build/release/.moc/moc_mediamanager.cpp: src/mediamanager.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mediamanager.h -o build/release/.moc/moc_mediamanager.cpp

build/release/.moc/moc_videolistwindow.cpp: src/videolistwindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/videolistwindow.h -o build/release/.moc/moc_videolistwindow.cpp

build/release/.moc/moc_videoplaywindow.cpp: src/videoplaywindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/videoplaywindow.h -o build/release/.moc/moc_videoplaywindow.cpp

build/release/.moc/moc_musicplayerwindow.cpp: src/musicplayerwindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/musicplayerwindow.h -o build/release/.moc/moc_musicplayerwindow.cpp

build/release/.moc/moc_radiowindow.cpp: src/radiowindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/radiowindow.h -o build/release/.moc/moc_radiowindow.cpp

build/release/.moc/moc_phonewindow.cpp: src/phonewindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/phonewindow.h -o build/release/.moc/moc_phonewindow.cpp

build/release/.moc/moc_diagnosticwindow.cpp: src/diagnosticwindow.h \
		src/mcuserialreader.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/diagnosticwindow.h -o build/release/.moc/moc_diagnosticwindow.cpp

build/release/.moc/moc_systemsettingwindow.cpp: src/systemsettingwindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/systemsettingwindow.h -o build/release/.moc/moc_systemsettingwindow.cpp

build/release/.moc/moc_drivingimagewindow.cpp: src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimagewindow.h -o build/release/.moc/moc_drivingimagewindow.cpp

build/release/.moc/moc_drivingimagenavbar.cpp: src/drivingimagenavbar.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimagenavbar.h -o build/release/.moc/moc_drivingimagenavbar.cpp

build/release/.moc/moc_drivingimagepreviewtopbar.cpp: src/drivingimagepreviewtopbar.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimagepreviewtopbar.h -o build/release/.moc/moc_drivingimagepreviewtopbar.cpp

build/release/.moc/moc_drivingimagesubtopbar.cpp: src/drivingimagesubtopbar.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimagesubtopbar.h -o build/release/.moc/moc_drivingimagesubtopbar.cpp

build/release/.moc/moc_drivingimagesettingspage.cpp: src/drivingimagesettingspage.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimagesettingspage.h -o build/release/.moc/moc_drivingimagesettingspage.cpp

build/release/.moc/moc_drivingimageplaybackpage.cpp: src/drivingimageplaybackpage.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/drivingimageplaybackpage.h -o build/release/.moc/moc_drivingimageplaybackpage.cpp

build/release/.moc/moc_ahdsettings.cpp: src/ahdsettings.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ahdsettings.h -o build/release/.moc/moc_ahdsettings.cpp

build/release/.moc/moc_imageviewingwindow.cpp: src/imageviewingwindow.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/imageviewingwindow.h -o build/release/.moc/moc_imageviewingwindow.cpp

build/release/.moc/moc_ahdmanager.cpp: src/ahdmanager.h \
		src/ahdlayout.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ahdmanager.h -o build/release/.moc/moc_ahdmanager.cpp

build/release/.moc/moc_ahdcamerapool.cpp: src/ahdcamerapool.h \
		src/ahdlayout.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ahdcamerapool.h -o build/release/.moc/moc_ahdcamerapool.cpp

build/release/.moc/moc_ahdpreviewwidget.cpp: src/ahdpreviewwidget.h \
		src/ahdcamerapool.h \
		src/ahdlayout.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ahdpreviewwidget.h -o build/release/.moc/moc_ahdpreviewwidget.cpp

build/release/.moc/moc_otamanager.cpp: src/otamanager.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/otamanager.h -o build/release/.moc/moc_otamanager.cpp

build/release/.moc/moc_progressmonitor.cpp: src/progressmonitor.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/progressmonitor.h -o build/release/.moc/moc_progressmonitor.cpp

build/release/.moc/moc_appsignals.cpp: src/appsignals.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/appsignals.h -o build/release/.moc/moc_appsignals.cpp

build/release/.moc/moc_topbarwidget.cpp: src/topbarwidget.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/topbarwidget.h -o build/release/.moc/moc_topbarwidget.cpp

build/release/.moc/moc_mcuserialreader.cpp: src/mcuserialreader.h \
		build/release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/CarDesk/build/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/CarDesk -I/data/CarDesk/src -I/data/CarDesk/thirdparty/mupdf/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mcuserialreader.h -o build/release/.moc/moc_mcuserialreader.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/release/.obj/main.o: src/main.cpp src/backlight.h \
		src/t507sdkbridge.h \
		src/mainwindow.h \
		src/mediamanager.h \
		src/phonewindow.h \
		src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/musicplayerwindow.h \
		src/radiowindow.h \
		src/videolistwindow.h \
		src/videoplaywindow.h \
		src/devicedetect.h \
		src/appsignals.h \
		src/mcuserialreader.h \
		src/automotivedriving.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/main.o src/main.cpp

build/release/.obj/automotivedriving.o: src/automotivedriving.cpp src/automotivedriving.h \
		src/ahdsettings.h \
		src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/mainwindow.h \
		src/mediamanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/automotivedriving.o src/automotivedriving.cpp

build/release/.obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/pagebgwidget.h \
		src/devicedetect.h \
		src/appsignals.h \
		src/bluetoothmanager.h \
		src/mediamanager.h \
		src/phonewindow.h \
		src/radiowindow.h \
		src/diagnosticwindow.h \
		src/mcuserialreader.h \
		src/systemsettingwindow.h \
		src/automotivedriving.h \
		src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/imageviewingwindow.h \
		src/videolistwindow.h \
		src/musicplayerwindow.h \
		src/topbarwidget.h \
		src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/mainwindow.o src/mainwindow.cpp

build/release/.obj/devicedetect.o: src/devicedetect.cpp src/devicedetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/devicedetect.o src/devicedetect.cpp

build/release/.obj/bluetoothmanager.o: src/bluetoothmanager.cpp src/bluetoothmanager.h \
		src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/bluetoothmanager.o src/bluetoothmanager.cpp

build/release/.obj/mediamanager.o: src/mediamanager.cpp src/mediamanager.h \
		src/bluetoothmanager.h \
		src/videolistwindow.h \
		src/videoplaywindow.h \
		src/musicplayerwindow.h \
		src/t507sdkbridge.h \
		src/radiowindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/mediamanager.o src/mediamanager.cpp

build/release/.obj/videolistwindow.o: src/videolistwindow.cpp src/videolistwindow.h \
		src/pagebgwidget.h \
		src/videoplaywindow.h \
		src/musicplayerwindow.h \
		src/devicedetect.h \
		src/topbarwidget.h \
		src/appsignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/videolistwindow.o src/videolistwindow.cpp

build/release/.obj/videoplaywindow.o: src/videoplaywindow.cpp src/videoplaywindow.h \
		src/bluetoothmanager.h \
		src/devicedetect.h \
		src/t507sdkbridge.h \
		src/appsignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/videoplaywindow.o src/videoplaywindow.cpp

build/release/.obj/musicplayerwindow.o: src/musicplayerwindow.cpp src/musicplayerwindow.h \
		src/pagebgwidget.h \
		src/bluetoothmanager.h \
		src/devicedetect.h \
		src/topbarwidget.h \
		src/appsignals.h \
		src/mediamanager.h \
		src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/musicplayerwindow.o src/musicplayerwindow.cpp

build/release/.obj/radiowindow.o: src/radiowindow.cpp src/radiowindow.h \
		src/devicedetect.h \
		src/topbarwidget.h \
		src/t507sdkbridge.h \
		src/appsignals.h \
		src/pagebgwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/radiowindow.o src/radiowindow.cpp

build/release/.obj/phonewindow.o: src/phonewindow.cpp src/phonewindow.h \
		src/pagebgwidget.h \
		src/bluetoothmanager.h \
		src/mediamanager.h \
		src/musicplayerwindow.h \
		src/videolistwindow.h \
		src/topbarwidget.h \
		src/appsignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/phonewindow.o src/phonewindow.cpp

build/release/.obj/diagnosticwindow.o: src/diagnosticwindow.cpp src/diagnosticwindow.h \
		src/mcuserialreader.h \
		src/mupdfdocument.h \
		src/pagebgwidget.h \
		src/devicedetect.h \
		src/faultcodedb.h \
		src/topbarwidget.h \
		src/appsignals.h \
		src/pinyin_dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/diagnosticwindow.o src/diagnosticwindow.cpp

build/release/.obj/systemsettingwindow.o: src/systemsettingwindow.cpp src/systemsettingwindow.h \
		src/pagebgwidget.h \
		src/bluetoothmanager.h \
		src/otamanager.h \
		src/devicedetect.h \
		src/topbarwidget.h \
		src/backlight.h \
		src/appsignals.h \
		src/t507sdkbridge.h \
		src/mcuserialreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/systemsettingwindow.o src/systemsettingwindow.cpp

build/release/.obj/drivingimagewindow.o: src/drivingimagewindow.cpp src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/automotivedriving.h \
		src/ahdpreviewwidget.h \
		src/ahdcamerapool.h \
		src/ahdsettings.h \
		src/pagebgwidget.h \
		src/drivingimagenavbar.h \
		src/drivingimageplaybackpage.h \
		src/drivingimagesettingspage.h \
		src/drivingimagepreviewtopbar.h \
		src/devicedetect.h \
		src/mainwindow.h \
		src/mediamanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimagewindow.o src/drivingimagewindow.cpp

build/release/.obj/drivingimagenavbar.o: src/drivingimagenavbar.cpp src/drivingimagenavbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimagenavbar.o src/drivingimagenavbar.cpp

build/release/.obj/drivingimagepreviewtopbar.o: src/drivingimagepreviewtopbar.cpp src/drivingimagepreviewtopbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimagepreviewtopbar.o src/drivingimagepreviewtopbar.cpp

build/release/.obj/drivingimagesubtopbar.o: src/drivingimagesubtopbar.cpp src/drivingimagesubtopbar.h \
		src/topbarwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimagesubtopbar.o src/drivingimagesubtopbar.cpp

build/release/.obj/drivingimagesettingspage.o: src/drivingimagesettingspage.cpp src/drivingimagesettingspage.h \
		src/ahdrecordstore.h \
		src/ahdsettings.h \
		src/drivingimagesubtopbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimagesettingspage.o src/drivingimagesettingspage.cpp

build/release/.obj/drivingimageplaybackpage.o: src/drivingimageplaybackpage.cpp src/drivingimageplaybackpage.h \
		src/ahdrecordstore.h \
		src/drivingimagesubtopbar.h \
		src/drivingimagewindow.h \
		src/ahdmanager.h \
		src/ahdlayout.h \
		src/videoplaywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/drivingimageplaybackpage.o src/drivingimageplaybackpage.cpp

build/release/.obj/ahdsettings.o: src/ahdsettings.cpp src/ahdsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdsettings.o src/ahdsettings.cpp

build/release/.obj/ahdrecordstore.o: src/ahdrecordstore.cpp src/ahdrecordstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdrecordstore.o src/ahdrecordstore.cpp

build/release/.obj/imageviewingwindow.o: src/imageviewingwindow.cpp src/imageviewingwindow.h \
		src/pagebgwidget.h \
		src/devicedetect.h \
		src/topbarwidget.h \
		src/appsignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/imageviewingwindow.o src/imageviewingwindow.cpp

build/release/.obj/t507sdkbridge.o: src/t507sdkbridge.cpp src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/t507sdkbridge.o src/t507sdkbridge.cpp

build/release/.obj/ahdmanager.o: src/ahdmanager.cpp src/ahdmanager.h \
		src/ahdlayout.h \
		src/ahdcamerapool.h \
		src/ahdpreviewwidget.h \
		src/ahdsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdmanager.o src/ahdmanager.cpp

build/release/.obj/ahdlayout.o: src/ahdlayout.cpp src/ahdlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdlayout.o src/ahdlayout.cpp

build/release/.obj/ahdcamerapool.o: src/ahdcamerapool.cpp src/ahdcamerapool.h \
		src/ahdlayout.h \
		src/ahdsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdcamerapool.o src/ahdcamerapool.cpp

build/release/.obj/ahdpreviewwidget.o: src/ahdpreviewwidget.cpp src/ahdpreviewwidget.h \
		src/ahdcamerapool.h \
		src/ahdlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/ahdpreviewwidget.o src/ahdpreviewwidget.cpp

build/release/.obj/otamanager.o: src/otamanager.cpp src/otamanager.h \
		src/progressmonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/otamanager.o src/otamanager.cpp

build/release/.obj/progressmonitor.o: src/progressmonitor.cpp src/progressmonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/progressmonitor.o src/progressmonitor.cpp

build/release/.obj/appsignals.o: src/appsignals.cpp src/appsignals.h \
		src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/appsignals.o src/appsignals.cpp

build/release/.obj/topbarwidget.o: src/topbarwidget.cpp src/topbarwidget.h \
		src/appsignals.h \
		src/t507sdkbridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/topbarwidget.o src/topbarwidget.cpp

build/release/.obj/faultcodedb.o: src/faultcodedb.cpp src/faultcodedb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/faultcodedb.o src/faultcodedb.cpp

build/release/.obj/mcuserialreader.o: src/mcuserialreader.cpp src/mcuserialreader.h \
		src/appsignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/mcuserialreader.o src/mcuserialreader.cpp

build/release/.obj/backlight.o: src/backlight.cpp src/backlight.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/backlight.o src/backlight.cpp

build/release/.obj/mupdfdocument.o: src/mupdfdocument.cpp src/mupdfdocument.h \
		thirdparty/mupdf/include/mupdf/fitz.h \
		thirdparty/mupdf/include/mupdf/fitz/version.h \
		thirdparty/mupdf/include/mupdf/fitz/config.h \
		thirdparty/mupdf/include/mupdf/fitz/system.h \
		thirdparty/mupdf/include/mupdf/fitz/export.h \
		thirdparty/mupdf/include/mupdf/memento.h \
		thirdparty/mupdf/include/mupdf/fitz/track-usage.h \
		thirdparty/mupdf/include/mupdf/fitz/context.h \
		thirdparty/mupdf/include/mupdf/fitz/geometry.h \
		thirdparty/mupdf/include/mupdf/fitz/output.h \
		thirdparty/mupdf/include/mupdf/fitz/buffer.h \
		thirdparty/mupdf/include/mupdf/fitz/string-util.h \
		thirdparty/mupdf/include/mupdf/fitz/stream.h \
		thirdparty/mupdf/include/mupdf/fitz/log.h \
		thirdparty/mupdf/include/mupdf/fitz/options.h \
		thirdparty/mupdf/include/mupdf/fitz/pool.h \
		thirdparty/mupdf/include/mupdf/fitz/crypt.h \
		thirdparty/mupdf/include/mupdf/fitz/getopt.h \
		thirdparty/mupdf/include/mupdf/fitz/hash.h \
		thirdparty/mupdf/include/mupdf/fitz/tree.h \
		thirdparty/mupdf/include/mupdf/fitz/bidi.h \
		thirdparty/mupdf/include/mupdf/fitz/xml.h \
		thirdparty/mupdf/include/mupdf/fitz/archive.h \
		thirdparty/mupdf/include/mupdf/fitz/json.h \
		thirdparty/mupdf/include/mupdf/fitz/hyphen.h \
		thirdparty/mupdf/include/mupdf/fitz/types.h \
		thirdparty/mupdf/include/mupdf/fitz/text.h \
		thirdparty/mupdf/include/mupdf/fitz/font.h \
		thirdparty/mupdf/include/mupdf/fitz/color.h \
		thirdparty/mupdf/include/mupdf/fitz/store.h \
		thirdparty/mupdf/include/mupdf/fitz/path.h \
		thirdparty/mupdf/include/mupdf/fitz/compress.h \
		thirdparty/mupdf/include/mupdf/fitz/pixmap.h \
		thirdparty/mupdf/include/mupdf/fitz/separation.h \
		thirdparty/mupdf/include/mupdf/fitz/compressed-buffer.h \
		thirdparty/mupdf/include/mupdf/fitz/filter.h \
		thirdparty/mupdf/include/mupdf/fitz/heap.h \
		thirdparty/mupdf/include/mupdf/fitz/heap-imp.h \
		thirdparty/mupdf/include/mupdf/fitz/image.h \
		thirdparty/mupdf/include/mupdf/fitz/bitmap.h \
		thirdparty/mupdf/include/mupdf/fitz/shade.h \
		thirdparty/mupdf/include/mupdf/fitz/glyph.h \
		thirdparty/mupdf/include/mupdf/fitz/device.h \
		thirdparty/mupdf/include/mupdf/fitz/display-list.h \
		thirdparty/mupdf/include/mupdf/fitz/structured-text.h \
		thirdparty/mupdf/include/mupdf/fitz/transition.h \
		thirdparty/mupdf/include/mupdf/fitz/glyph-cache.h \
		thirdparty/mupdf/include/mupdf/fitz/link.h \
		thirdparty/mupdf/include/mupdf/fitz/outline.h \
		thirdparty/mupdf/include/mupdf/fitz/document.h \
		thirdparty/mupdf/include/mupdf/fitz/util.h \
		thirdparty/mupdf/include/mupdf/fitz/writer.h \
		thirdparty/mupdf/include/mupdf/fitz/band-writer.h \
		thirdparty/mupdf/include/mupdf/fitz/write-pixmap.h \
		thirdparty/mupdf/include/mupdf/fitz/output-svg.h \
		thirdparty/mupdf/include/mupdf/fitz/story.h \
		thirdparty/mupdf/include/mupdf/fitz/story-writer.h \
		thirdparty/mupdf/include/mupdf/fitz/deskew.h \
		thirdparty/mupdf/include/mupdf/fitz/barcode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/mupdfdocument.o src/mupdfdocument.cpp

build/release/.obj/pinyin_dictionary.o: src/pinyin_dictionary.cpp src/pinyin_dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/pinyin_dictionary.o src/pinyin_dictionary.cpp

build/release/.obj/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/qrc_resources.o qrc_resources.cpp

build/release/.obj/moc_mainwindow.o: build/release/.moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_mainwindow.o build/release/.moc/moc_mainwindow.cpp

build/release/.obj/moc_bluetoothmanager.o: build/release/.moc/moc_bluetoothmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_bluetoothmanager.o build/release/.moc/moc_bluetoothmanager.cpp

build/release/.obj/moc_mediamanager.o: build/release/.moc/moc_mediamanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_mediamanager.o build/release/.moc/moc_mediamanager.cpp

build/release/.obj/moc_videolistwindow.o: build/release/.moc/moc_videolistwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_videolistwindow.o build/release/.moc/moc_videolistwindow.cpp

build/release/.obj/moc_videoplaywindow.o: build/release/.moc/moc_videoplaywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_videoplaywindow.o build/release/.moc/moc_videoplaywindow.cpp

build/release/.obj/moc_musicplayerwindow.o: build/release/.moc/moc_musicplayerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_musicplayerwindow.o build/release/.moc/moc_musicplayerwindow.cpp

build/release/.obj/moc_radiowindow.o: build/release/.moc/moc_radiowindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_radiowindow.o build/release/.moc/moc_radiowindow.cpp

build/release/.obj/moc_phonewindow.o: build/release/.moc/moc_phonewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_phonewindow.o build/release/.moc/moc_phonewindow.cpp

build/release/.obj/moc_diagnosticwindow.o: build/release/.moc/moc_diagnosticwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_diagnosticwindow.o build/release/.moc/moc_diagnosticwindow.cpp

build/release/.obj/moc_systemsettingwindow.o: build/release/.moc/moc_systemsettingwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_systemsettingwindow.o build/release/.moc/moc_systemsettingwindow.cpp

build/release/.obj/moc_drivingimagewindow.o: build/release/.moc/moc_drivingimagewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimagewindow.o build/release/.moc/moc_drivingimagewindow.cpp

build/release/.obj/moc_drivingimagenavbar.o: build/release/.moc/moc_drivingimagenavbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimagenavbar.o build/release/.moc/moc_drivingimagenavbar.cpp

build/release/.obj/moc_drivingimagepreviewtopbar.o: build/release/.moc/moc_drivingimagepreviewtopbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimagepreviewtopbar.o build/release/.moc/moc_drivingimagepreviewtopbar.cpp

build/release/.obj/moc_drivingimagesubtopbar.o: build/release/.moc/moc_drivingimagesubtopbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimagesubtopbar.o build/release/.moc/moc_drivingimagesubtopbar.cpp

build/release/.obj/moc_drivingimagesettingspage.o: build/release/.moc/moc_drivingimagesettingspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimagesettingspage.o build/release/.moc/moc_drivingimagesettingspage.cpp

build/release/.obj/moc_drivingimageplaybackpage.o: build/release/.moc/moc_drivingimageplaybackpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_drivingimageplaybackpage.o build/release/.moc/moc_drivingimageplaybackpage.cpp

build/release/.obj/moc_ahdsettings.o: build/release/.moc/moc_ahdsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_ahdsettings.o build/release/.moc/moc_ahdsettings.cpp

build/release/.obj/moc_imageviewingwindow.o: build/release/.moc/moc_imageviewingwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_imageviewingwindow.o build/release/.moc/moc_imageviewingwindow.cpp

build/release/.obj/moc_ahdmanager.o: build/release/.moc/moc_ahdmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_ahdmanager.o build/release/.moc/moc_ahdmanager.cpp

build/release/.obj/moc_ahdcamerapool.o: build/release/.moc/moc_ahdcamerapool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_ahdcamerapool.o build/release/.moc/moc_ahdcamerapool.cpp

build/release/.obj/moc_ahdpreviewwidget.o: build/release/.moc/moc_ahdpreviewwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_ahdpreviewwidget.o build/release/.moc/moc_ahdpreviewwidget.cpp

build/release/.obj/moc_otamanager.o: build/release/.moc/moc_otamanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_otamanager.o build/release/.moc/moc_otamanager.cpp

build/release/.obj/moc_progressmonitor.o: build/release/.moc/moc_progressmonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_progressmonitor.o build/release/.moc/moc_progressmonitor.cpp

build/release/.obj/moc_appsignals.o: build/release/.moc/moc_appsignals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_appsignals.o build/release/.moc/moc_appsignals.cpp

build/release/.obj/moc_topbarwidget.o: build/release/.moc/moc_topbarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_topbarwidget.o build/release/.moc/moc_topbarwidget.cpp

build/release/.obj/moc_mcuserialreader.o: build/release/.moc/moc_mcuserialreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_mcuserialreader.o build/release/.moc/moc_mcuserialreader.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

